spring.application.name=spring-security-demo
springdoc.api-docs.version=openapi_3_0


spring.datasource.url=jdbc:postgresql://localhost:3308/SECURITY_DEMO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=root123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
# Access token validity (in seconds)
jwt.access.expiration=60

# Refresh token validity (in seconds)
jwt.refresh.expiration=604800
aes.secret.key=8tBgHTNdxAWGfqfwhojyrKhmXj2dKX8gRAzEcG0nKpE=


#################### Redis ###################
spring.data.redis.host=localhost
spring.data.redis.port=6379

#################### OAuth2 Client (Social Login) ###################
# Google
spring.security.oauth2.client.registration.google.client-id889236787041-2u1voqr5s66s7js3freq7rhlrgf3u9fd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secretGOCSPX--6iM3sZskNXIPT0QcUtMI5lhyUuN
spring.security.oauth2.client.registration.google.scope=email,profile

# GitHub
spring.security.oauth2.client.registration.github.client-idOv23lihMLS7ySm4ResLu
spring.security.oauth2.client.registration.github.client-secret0cfd7fa4b5e78a3542147b7453211d0ebc7ecf6e
spring.security.oauth2.client.registration.github.scope=email,profile

# Frontend redirect after login
app.frontend.url=http://localhost:4200